name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write 

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm run test -- --run
      
    - name: Type check
      run: npm run typecheck
      
    - name: Build library  
      run: npm run build
      
    - name: Verify package contents
      run: npm pack --dry-run
      
    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Changes in this Release
          
          * New framework adapters for React, Vue, and Angular
          * TypeScript support with full type definitions
          * Enhanced user education features
          * Performance improvements and bug fixes
          
          ## Installation
          
          ```bash
          npm install @andreaswissel/uiflow@${{ github.ref }}
          ```
          
          ## Framework Adapters
          
          - React: `import { UIFlowProvider } from '@andreaswissel/uiflow/adapters/react'`
          - Vue: `import { createUIFlow } from '@andreaswissel/uiflow/adapters/vue'`
          - Angular: `import { UIFlowModule } from '@andreaswissel/uiflow/adapters/angular'`
          
          See the [documentation](https://github.com/andreaswissel/uiflow/tree/main/docs) for full usage examples.
        draft: false
        prerelease: false

  deploy-docs:
    runs-on: ubuntu-latest
    needs: release
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build demo
      run: npm run build
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./demo
        publish_branch: gh-pages
        
    - name: Update package registry
      run: |
        echo "Documentation deployed to GitHub Pages"
        echo "Demo available at: https://andreaswissel.github.io/uiflow"
